### PR TITLE
[ProblemSolver] Wrap in python idl method related to contact surfaces.

### PR DESCRIPTION
**Pull request by florent-lamiraux**
- Wrap in python the following idl methods
    - Problem::getEnvironmentContact,
    - Problem::getEnvironmentContactNames,
    - Problem::getRobotContact,
    - Problem::getRobotContactNames.

  - Document those methods and the corresponding idl interfaces.

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
@jmirabel, could you check the comment of the methods, I am not sure.

**Comment by florent-lamiraux** [comment]
Thank you.
I was actually talking about the documentation of "getEnvironmentContact" and "getRobotContact".
I do not quite understand the type of the result: the input is the contact surface name, but the output is a list of 3 elements:
1.  a list of joint names (I would expect a joint name)
2. a list of indices (I would expect one index),
3. a list of vertices (as I would expect).

**Comment by jmirabel** [comment]
I see.
Maybe a pointer to the hpp-manipulation-urdf would help then.

From the example in the doc,
```xml
<contact name="name">
    <link name="link_name" />
  <!-- Exactly 1 -->
    <!-- Sequence of 3D points expressed in the frame defined above -->
    <point>-0.025 -0.025 -0.025   -0.025 0.025 -0.025   -0.025 -0.025 0.025   -0.025 0.025 0.025 </point>
    <!-- Sequence of planar shape.
         Shapes are defined by a sequence of points to be connected (consecutively).
         For a shape defined by N points, N+1 values must be provided in this tag:
         N iPoint_1 ... iPoint_N
         WARNING: Shapes 3 0 1 2 and 3 0 2 1 are different because their respective orientations are opposites.
         firstSegment ^ secondSegment must points outside the object -->
    <shape> 3 0 2 1 3 2 1 3</shape>
</contact>
```
you should get [ 3, 3 ] as list of integers.

**Comment by jmirabel** [comment]
That means that the contact contains two polygons, each made of 3 points. The list of vertices should then be of size 6.

The output of this function should be modified:
- for something simpler that returns a list of vertices,
- for something more elaborated that returns what is in the SRDF.

This can be kept for later. I has impact on hpp-gui.

**Comment by florent-lamiraux** [comment]
Okay, I better understand. In the example below
`ps.getRobotContact('box/bottom_surface')

(['box/root_joint'],
 [4],
 [[-0.105, -0.071, 0.02],
  [-0.105, -0.071, -0.02],
  [0.105, -0.071, -0.02],
  [0.105, -0.071, 0.02]])
`
there is one contact surface with 4 vertices, right ?
If there were 2 surfaces : a triangle and a square, we would have [3,4] intead of [4] as the second element, and 7 points as the third element, right ?

Does it make sense to have a list of joints ? If two polygons are attached to different joints, they should be spit into two surfaces ?

**Comment by jmirabel** [comment]
After double checking the code, I believe the output with example from the doc is


> If there were 2 surfaces : a triangle and a square, we would have [3,4] intead of [4] as the second element, and 7 points as the third element, right ?

You would get
```
(['joint', 'joint'],
[3, 4],
[[-0.105, -0.071, 0.02],
[-0.105, -0.071, -0.02],
[0.105, -0.071, -0.02],
[0.105, -0.071, 0.02],
... # 3 other points
])
```

I am not sure why there are several joints. From the SRDF, the joint will be unique. The only place where I see a utility for having different joint names is when you have fixed joints and you want to place one shape into one joint A frame and the other in another joint B frame (with joint A fixed wrt joint B).

**Comment by jmirabel** [comment]
> I am not sure why there are several joints.

Likely, the reason is the following. I added this function to be able to plot the shapes in the GUI. In hpp-core, they are stored in a map of type
```c++
std::map<std::string,
  std::vector <
    std::pair <
      JointPtr_t,
      std::vector<core::vector3_t> // Shape_t
    > // JointAndShape_t
  > // JointAndShapes_t
>
```

I don't know why it isn't
```c++
std::map<std::string,
  std::pair <
    JointPtr_t,
    std::vector <
      std::vector<core::vector3_t> // Shape_t
    > // Shapes_t
  > // JointAndShapes_t
>
```

**Comment by florent-lamiraux** [comment]
I have updated the documentation according to what we discussed.

**Pull request merged**
